# Generated by Django 5.1.1 on 2024-10-06 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=10, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('grade', models.CharField(max_length=2)),
                ('homeroom', models.CharField(max_length=100)),
                ('homeroom_teacher', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='student_photos/')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/students/')),
                ('enrollment_status', models.BooleanField(default=True)),
            ],
        ),
    ]
