# Generated by Django 5.1.1 on 2024-10-06 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_alter_student_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='techbucks',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
