# Generated by Django 5.1.1 on 2024-10-06 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_student_techbucks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='techbucks',
            field=models.IntegerField(default=0),
        ),
    ]
