# Generated by Django 5.1.1 on 2024-10-07 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_student_techbucks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='techbucks',
        ),
    ]
