# Generated by Django 5.1.1 on 2024-10-06 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0003_remove_reward_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='unique_id',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
    ]
