# Generated by Django 5.1.1 on 2024-10-07 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0005_rename_redeemed_at_redemption_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='redemption',
            name='redeemed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
